#!/bin/sh
# embed-grammars.sh — generate src/grammar_blobs.cyr from grammars/*.cyml
#
# vyakarana ships dist/vyakarana.cyr as a self-contained bundle. The
# bundle's bootstrap_grammars() loads 38 grammars; without this step
# it would call file_read_all("grammars/<name>.cyml") at runtime,
# but cyrius deps doesn't vendor grammars/ — only the bundle. Inlining
# the .cyml files as Cyrius string literals makes the bundle truly
# self-contained.
#
# Output: src/grammar_blobs.cyr — gitignored. Always regenerated; never
# hand-edited. Run before cyrius build / cyrius test / cyrius distlib.
#
# How the runtime uses it: src/grammar.cyr's grammar_load(path) calls
# _grammar_blob_data(path) first; if non-zero, parses from memory; else
# falls back to file_read_all (preserves the dev workflow of editing
# grammars/foo.cyml and re-running without regenerating blobs).

set -e

cd "$(dirname "$0")/.."

OUT="src/grammar_blobs.cyr"
GRAMMARS=$(ls grammars/*.cyml | sort)
COUNT=$(echo "$GRAMMARS" | wc -l)

# Header
cat > "$OUT" <<EOF
# vyakarana — embedded grammar blobs (auto-generated)
#
# AUTO-GENERATED by scripts/embed-grammars.sh — do not edit.
# Regenerate after editing any grammars/*.cyml file.
# Gitignored; produced fresh on each build / distlib step.
#
# Source: $COUNT grammars in grammars/*.cyml.
# Used by src/grammar.cyr's grammar_load() — checks blob lookup first,
# falls back to file_read_all() if no blob matches the path. Lets
# dist/vyakarana.cyr be a single self-contained bundle (cyrius deps
# vendors only the bundle file, not the grammars/ dir).
#
# Uses streq() from lib/string.cyr — auto-included via cyrius.cyml's
# [deps] stdlib (\`string\`).

EOF

# Per-grammar blob function. Body is the .cyml content as one Cyrius
# string literal — escape "\\", '"', NL, TAB, CR. Other control bytes
# don't appear in any current .cyml file (verified at script start);
# bail loudly if they ever do so we can revisit the encoding.
escape_one() {
    awk '
    {
        line = $0
        gsub(/\\/, "\\\\", line)
        gsub(/"/, "\\\"", line)
        gsub(/\t/, "\\t", line)
        gsub(/\r/, "\\r", line)
        printf "%s\\n", line
    }
    '
}

# Sanity: refuse to embed any file with a NUL or other unexpected
# control byte. .cyml files are text — anything else means something
# is wrong upstream.
for f in $GRAMMARS; do
    if LC_ALL=C grep -lP '[\x00-\x08\x0b\x0c\x0e-\x1f]' "$f" > /dev/null 2>&1; then
        echo "embed-grammars.sh: $f contains unexpected control bytes; refusing to embed" >&2
        exit 1
    fi
done

# Emit one fn per grammar. Path key matches what bootstrap_grammars
# passes to grammar_load(): "grammars/<name>.cyml".
i=0
for f in $GRAMMARS; do
    name=$(basename "$f" .cyml)
    # Cyrius idents — replace any non-alnum with _
    sym=$(printf '%s' "$name" | tr -c 'A-Za-z0-9_' '_' | tr -s '_')
    {
        printf 'fn _grammar_blob_%s() {\n' "$sym"
        printf '    return "'
        escape_one < "$f"
        printf '";\n'
        printf '}\n\n'
    } >> "$OUT"
    i=$((i + 1))
done

# Lookup: linear scan. 38 strcmp calls on init-only — fine.
{
    cat <<'EOF'
# Returns pointer to the blob's content (cstr) for the given path, or
# 0 if no blob matches. Path is the same string bootstrap_grammars
# passes to grammar_load() — "grammars/<name>.cyml".
fn _grammar_blob_data(path) {
EOF
    for f in $GRAMMARS; do
        name=$(basename "$f" .cyml)
        sym=$(printf '%s' "$name" | tr -c 'A-Za-z0-9_' '_' | tr -s '_')
        printf '    if (streq(path, "grammars/%s.cyml")) { return _grammar_blob_%s(); }\n' "$name" "$sym"
    done
    cat <<'EOF'
    return 0;
}

# Number of embedded grammars. Mostly a self-test hook — bootstrap
# expects this to match grammars/*.cyml at build time.
fn _grammar_blob_count() {
EOF
    printf '    return %d;\n' "$COUNT"
    cat <<'EOF'
}
EOF
} >> "$OUT"

echo "embed-grammars: wrote $OUT ($COUNT grammars, $(wc -c < "$OUT") bytes)"
