#!/bin/sh
# lint-fmt.sh — run cyrius lint and cyrius fmt --check across every
# hand-edited Cyrius source file in src/. Mandatory pre-release
# step (CLAUDE.md §Gates, §Closeout pass). CI runs the same set;
# either step failing blocks the release.
#
# Skips:
#   - src/grammar_blobs.cyr — auto-generated by
#     scripts/embed-grammars.sh; long string-literal lines are
#     intentional. CI's lint step already excludes it for the
#     same reason.

set -e

cd "$(dirname "$0")/.."

rc=0

for f in src/*.cyr src/grammars/*.cyr; do
    case "$f" in
        src/grammar_blobs.cyr) continue ;;
    esac
    if ! cyrius lint "$f"; then rc=1; fi
done

if [ "$rc" -ne 0 ]; then
    echo "lint-fmt: lint warnings — fix before release" >&2
    exit "$rc"
fi

for f in src/*.cyr src/grammars/*.cyr; do
    case "$f" in
        src/grammar_blobs.cyr) continue ;;
    esac
    if ! cyrius fmt "$f" --check > /dev/null 2>&1; then
        echo "lint-fmt: $f is not formatted (run 'cyrius fmt $f' to fix)" >&2
        rc=1
    fi
done

if [ "$rc" -eq 0 ]; then
    echo "lint-fmt: OK — all src/*.cyr lint-clean and formatted"
fi

exit "$rc"
