# Vidya — Lexing and Parsing in Terraform / HCL
#
# Terraform's HCL is a declarative configuration language: you
# describe *what* infrastructure you want, the planner decides
# *how* to get there. A "tokenizer" here is conceptual — the
# config below just sets up the data the planner walks. The
# Vidya tokenizer-themed structure mirrors the lexer / parser
# split in real Terraform internals.

terraform {
  required_version = ">= 1.6.0"

  required_providers {
    aws = {
      source  = "hashicorp/aws"
      version = "~> 5.0"
    }
  }

  backend "s3" {
    bucket = "lexer-demo-tfstate"
    key    = "lexer/terraform.tfstate"
    region = "us-east-1"
  }
}


// Both `#` and `//` are valid line comments in HCL. Most
// real-world Terraform uses `#`; tools generated by go's HCL
// libraries often use `//`.
provider "aws" {
  region = var.region
}


variable "region" {
  type        = string
  default     = "us-east-1"
  description = "AWS region for the demo resources."
}


variable "environments" {
  type    = list(string)
  default = ["dev", "staging", "prod"]
}


/* Locals are computed values, useful for keeping repeated
   expressions DRY. They evaluate once per plan. */
locals {
  prefix = "lexer-demo"
  tags = {
    Project     = local.prefix
    Environment = "demo"
    ManagedBy   = "terraform"
  }
}


# Dynamic block iteration — generates one S3 bucket per
# environment via `for_each`. The `each.key` lookup inside the
# resource references the iteration variable.
resource "aws_s3_bucket" "tokens" {
  for_each = toset(var.environments)

  bucket = "${local.prefix}-${each.key}-tokens"
  tags   = merge(local.tags, { Stage = each.key })
}


resource "aws_s3_bucket_versioning" "tokens" {
  for_each = aws_s3_bucket.tokens

  bucket = each.value.id
  versioning_configuration {
    status = each.value.tags.Stage == "prod" ? "Enabled" : "Suspended"
  }
}


# Dynamic blocks expand into zero-or-more nested blocks based
# on a collection. Useful for IAM-like configs where the
# number of nested blocks depends on input.
resource "aws_iam_policy_document" "tokens_read" {
  dynamic "statement" {
    for_each = aws_s3_bucket.tokens

    content {
      sid    = "Read${replace(statement.value.tags.Stage, "/-/", "")}"
      effect = "Allow"

      actions = [
        "s3:GetObject",
        "s3:ListBucket",
      ]

      resources = [
        statement.value.arn,
        "${statement.value.arn}/*",
      ]
    }
  }
}


# Outputs surface values for downstream consumers (other
# Terraform modules, the CLI's `terraform output`, CI).
output "bucket_arns" {
  description = "ARNs of the per-environment token buckets."
  value       = [for b in aws_s3_bucket.tokens : b.arn]
}


output "primary_bucket" {
  value = aws_s3_bucket.tokens["prod"].id
}
